blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

blogger_api:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /

#api:
#    type: rest
#    resource: "routing_api.yml"




