# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Blogger\BlogBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER



    providers:
        main:
            entity: { class: BloggerBlogBundle:User, property: username}

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true

        api_docs:
           pattern: ^/doc
           anonymous: true

        dev:
              pattern: ^/(_(profiler|wdt)|css|images|js)/
              security: false

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
       #- { path: /api/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

